### ISSUE TITLE
Fairground Incentive Front End Feedback

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/token-frontend#731]
Below is a summary of the feedback I've found so far.   Dont know if you need details of PubKey to diagnose the first couple so have included.  The others are minor UX / cosmetic things. 

Twitter handle @JonRay_15
Vega PubKey = fc959aadac95f0f456685346d5aa5304e5180391c6ebc0508bed3c0fcdf26dff

1. Failed staking 
At the moment it is quite hard as a user to know where you can stake to and how much.  
Last night I tried to stake 1.50 to Marvin, but when I checked back at the next epoch I still have 1.50 unstaked. 
I then tried to stake that 1.50 again in the next epoch, but when I checked back only 0.03999 had staked and 1.46666 was still unstaked.
A) Is this because the validator was full or because there has been some sort of failure / bug?
B) If it IS because the validator is full, how as a user do I know that?  Could we have a message indicating that is why X amount is still unstaked?
(EDIT: At the time of the latest epoch the total stake on Marvin is now up to 190 VEGA which is way higher than it was when I attempted both my previous delegations, therefore I suspect this is not due to the validator being "full" and is in fact some sort of failure to stake)
(SECOND EDIT: ignore my first edit; have confirmed with Zohar that max is a moving target, and that was indeed the reason my stake got rejected, so it is just a question of how / if we can make that process a bit more intuitive for users.)

2. Where to stake 
Following on from the above, if validators are filling up, how do I know where I can stake where i'll be less at risk of being hit by the above?
I've now tried twice to stake to Marvin, and both times basically failed to stak anything, thats 2 wasted epochs, a full 48 hours in the real world.
How do we help users avoid this?  I cant see anywhere currently that shows me the total stake available at a validator or how "full" they are?
I see total stake and pending stake, but without the max allowable stake both those numbers are fairly meaningless from a user perspective.

3. Decimals generally 
We have too many on basically all numeric fields.  Makes it hard to read, and in the bottom validator panels throws off the alignment. 
We should trim all numeric fields to some sensible number of decimals, whatever we think that is. 

4. Alignment of the validator summary table 
Linked to 3, the alignment of the table is off, both due to decimals and due to variable length of the validator name.
Can we standardise it all and avoid the text wrapping where possible.
Similar text wrapping issues occur at the table at the top with long strings for pubKeys, cant we vary the text size by screen size?

5. Epoch status 
Would it make sense to have the epoch progress bar on the main Staking page rather than having to click into the individual validator to see this?  Presumably epoch is shared across all?

**Comment by campbellssource** [comment]
@JonRay15 Thanks for raising this ticket. I'll over the new few days respond to some of the points with links to tickets for work we plan to do that should fix these issues, and break any individual issues into their own tickets.

**Comment by JonRay15** [comment]
@campbellssource noticing on the new testnet version the decimal point is still not resolved, which is again leading to confusing text wrapping on the validator screen.  Did that issue get prioritised? Same issue still on the validator page, stake share showing to I think 18 decimal places (3.158179906505126709% is hard to read).

**Comment by campbellssource** [comment]
@JonRay15 token.fairground.wtf has not been updated as the version of Core on fairground now old and won't work with latest.
here is a preview of what the newer layer. more improvements also coming.

<img width="841" alt="Screenshot 2021-11-17 at 18 13 25" src="https://user-images.githubusercontent.com/13255539/142258299-6cff41d5-ab1d-4969-81e2-fb5e185d9041.png">

#880 and potentially a whole new layout with lots of improvements.
