### ISSUE TITLE
GQL Subscriptions not working - Awaiting new Data node

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/token-frontend#959]
GQL subscriptions are not working on MAINNET.

We have refactored the existing functionality to poll instead of using subscriptions, so no functionality is broken as of now.

Going forward we would certainly prefer to use subscriptions. This is a ticket to track that.

@edd had a go at proxying the traffic but this was not working as we would hope.

We need to decide how we want to fix this.

**Comment by dexturr** [comment]
Blocked by https://github.com/vegaprotocol/devops-infra/issues/950

**Comment by dexturr** [comment]
The above issue is resolved and this PR will point us at the vega data node:
https://github.com/vegaprotocol/token-frontend-api-proxy/pull/3

**Comment by dexturr** [comment]
This is now blocked by vegaprotocol/devops-infra#1072, until we get HTTPS Websockets will not work

**Comment by campbellssource** [comment]
https://github.com/vegaprotocol/devops-infra/issues/1072 has been marked as closed, but I note that http://mainnet-observer.ops.vega.xyz:3008/playground still doesn't have a https:// have asked what this means.

side node: There is another potential solution to this: https://github.com/vegaprotocol/data-node/issues/295
